#!/bin/bash

# oraORDS.sh

# select ords.installed_version from dual;
#
# Internal settings
SCRIPTVER=1.0
SCRIPTNAME=$(basename "${BASH_SOURCE[0]}")
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/oralab.shlib

# static defaults
ords_path=/u01/app/oracle/product/ords
ords_src=/mnt/software/Oracle/ords/ords-22.4.0.r3401044.zip
ords_port=8443
ords_admin=/u01/app/oracle/admin/ords
ORDS_CONFIG=${ords_admin}/config
ords_logs=${ords_admin}/logs

db_host=$( hostname -f )
db_port=1521
db_service=pdb1
sys_password=xxxx

# verify that we are root to run this script
if [ "x$USER" != "xroot" ];then logMesg 1 "You must be logged in as root to run this script" E "NONE"; exit 1; fi

# check if the ORDS install file is there
if [ -f "${ords_src}" ]; then

    # install java if it is not arlready installed
    #   Note lsof used by systemctl start script for ords
    yum -y install java-11-openjdk lsof
    if (( $? > 0 )) ; then echo "ERROR could not install Java 11"; exit 1; fi

    # create the target directories
    [[ ! -d "${ords_path}" ]] && mkdir -p "${ords_path}"
    [[ ! -d "${ords_admin}" ]] && mkdir -p "${ords_admin}"
    [[ ! -d "${ORDS_CONFIG}" ]] && mkdir -p "${ORDS_CONFIG}"
    [[ ! -d "${ords_logs}" ]] && mkdir -p "${ords_logs}"
    chown oracle:oinstall "${ords_path}"
    chown oracle:oinstall "${ords_admin}"
    chown oracle:oinstall "${ORDS_CONFIG}"
    chown oracle:oinstall "${ords_logs}"

    # load the ORDS software
    unzip "${ords_src}" -d "${ords_path}"

    # Install ORDS into the database
    echo "ORDS CONFIG: ${ORDS_CONFIG}"
    export ORDS_CONFIG
    ords_features="--feature-sdw true --log-folder ${ords_logs}"
    ords_db="--admin-user SYS --password-stdin --db-hostname ${db_host} --db-port ${db_port} --db-servicename ${db_service}"
    ords_storage="--schema-tablespace SYSAUX --schema-temp-tablespace TEMP"
    echo "ORDS COMMAND LINE: ${ords_path}/bin/ords install ${ords_features} ${ords_db} ${ords_storage}"
    /usr/bin/su oracle -c "echo ${sys_password} | ${ords_path}/bin/ords install ${ords_features} ${ords_db} ${ords_storage}"

    # Configure ORDS standalone server
    /usr/bin/su oracle -c "${ords_path}/bin/ords config set standalone.https.host $( hostname -f )"
    /usr/bin/su oracle -c "${ords_path}/bin/ords config set standalone.https.port ${ords_port}"

    # Configure ORDS auto start
    # Create configuration file
    #   Note ORDS_BASE is the directory under "ords" used by systemctl start
    echo "# ORDS Service Script Configuration File (ords.config)" > /etc/ords.conf
    echo "# Generated by oraORDS.sh $( date )"                    >> /etc/ords.conf
    echo "ORDS_BASE=$( dirname ${ords_path} )"                    >> /etc/ords.conf
    echo "ORDS_CONFIG=${ORDS_CONFIG}"                             >> /etc/ords.conf
    echo "SERVE_EXTRA_ARGS=--port ${ords_port} --secure"          >> /etc/ords.conf
    chown oracle:oinstall /etc/ords.conf
    chmod 750 /etc/ords.conf

    # copy man pages
    cp "${ords_path}"/linux-support/man/ords.1 /usr/share/man/man1/ords.1.gz
    chmod 644 /usr/share/man/man1/ords.1.gz
    chown root:root /usr/share/man/man1/ords.1.gz
    cp "${ords_path}"/linux-support/man/ords.conf.5 /usr/share/man/man5/ords.conf.5.gz
    chmod 644 /usr/share/man/man5/ords.conf.5.gz
    chown root:root /usr/share/man/man5/ords.conf.5.gz
    cp "${ords_path}"/linux-support/man/ords.service.8 /usr/share/man/man8/ords.service.8.gz
    chmod 644 /usr/share/man/man8/ords.service.8.gz
    chown root:root /usr/share/man/man8/ords.service.8.gz

    # create autostart
    cp "${ords_path}"/linux-support/ords.sh /etc/init.d/ords
    chown root:root /etc/init.d/ords
    chmod 755 /etc/init.d/ords
    cp "${ords_path}"/linux-support/ords.service /etc/systemd/system/ords.service
    chown root:root /etc/systemd/system/ords.service
    chmod 644 /etc/systemd/system/ords.service
    ln -s "${ords_path}"/bin/ords /usr/local/bin/ords

    # fix autostart bugs
    sed -i 's/_ords_base > 0/_ords_base -gt 0/g' /etc/init.d/ords

    # enable autostart
    case "$( ps --no-headers -o comm 1 )" in
        'systemd') 
            systemctl enable ords
            systemctl start ords
            ;;
        'init') 
            chkconfig --add ords
            service ords start
            ;;
        *) 
            echo "ERROR autostart not supported on this platform"
            echo "   You will need to manually start ORDS       "
            ;;
    esac

    # configure firewall
    /bin/firewall-cmd --permanent --zone=public --add-port=${ords_port}/tcp
    /bin/firewall-cmd --reload

else
    echo "ERROR! could not find ORDS install file at: ${ords_src}"
    exit 1
fi

# Uninstall options
# ords --config /path/to/test/config uninstall --admin-user SYS --db-hostname localhost --db-port 1521 --db-servicename orcl --log-folder /path/to/logs

# END
