#!/bin/bash

# oraRWLInst.sh

# https://github.com/oracle/rwloadsim

# source binary files
src_file=rwloadsim-linux-x86_64-bin-3.0.5.tgz
src_url=https://github.com/oracle/rwloadsim/releases/download/v3.0.5/rwloadsim-linux-x86_64-bin-3.0.5.tgz

# RWL locations
rwl_dir=/u01/app/oracle/rwloadsim
rwl_output=/u01/app/oracle/admin/rwlout

# databae information
my_project=pdb1
my_db=pdb1
my_cdb=t1db

system_password=xxxx
rwl_password=xxxx

############################################################################################
# start here

# verify that we are root to run this script
if [ "x$USER" != "xroot" ];then logMesg 1 "You must be logged in as root to run this script" E "NONE"; exit 1; fi

db_url="//$( hostname -f ):1521/${my_db}"
cdb_url="//$( hostname -f ):1521/${my_cdb}"

# install required GNUPlot software
yum -y install gnuplot

# install the RWL binaries
mkdir -p "${rwl_dir}"
wget "${src_url}" 
tar -xvzf "${src_file}" -C $"${rwl_dir}"

# setup the location files
rwl_results=${rwl_output}/results/${my_project}
rwl_out=${rwl_output}/html/${my_project}
rwl_work=${rwl_output}/workdir/${my_project}

mkdir -p "${rwl_results}"
mkdir -p "${rwl_out}"
mkdir -p "${rwl_work}"

# setup env file
rwl_env="${rwl_work}/${my_project}.env"
# cp "${rwl_dir}/oltp/oltp.env" "${rwl_work}/${my_project}.env"
echo "# rwloadsim config file for OLTP "   >  "${rwl_env}"
echo "#  Generated by oraRWL.sh script  "   >> "${rwl_env}"
echo "export RWLOLTP_NAME=${my_project} "  >> "${rwl_env}"
echo "export RWLOADSIM_PATH=${rwl_work} "  >> "${rwl_env}"
echo "#  Adding RWLoadSim into path    "   >> "${rwl_env}"
echo "export PATH=\$PATH:${rwl_dir}/bin "  >> "${rwl_env}"
echo "#  For -g option to set gnuplot geometry"   >> "${rwl_env}"
echo "export RWLOLTP_GNUPLOT1='-geometry 640x350+0+0'"   >> "${rwl_env}"
echo "export RWLOLTP_GNUPLOT2='-geometry 640x350+0+400'"   >> "${rwl_env}"

# cp "${rwl_dir}/oltp/oltp.rwl" "${rwl_work}/${my_project}.rwl"

rwl_rwl="${rwl_work}/${my_project}.rwl"
echo "# rwloadsim rwl file for OLTP           "                >  "${rwl_rwl}"
echo "#  Generated by oraWL.sh script         "                >> "${rwl_rwl}"
echo "# name of the directory where awr, html, graphs"         >> "${rwl_rwl}"
echo "awrdirectory := \"${rwl_out}\";"                         >> "${rwl_rwl}"
echo "# name of the results directory"                         >> "${rwl_rwl}"
echo "resultsdir:=\"${rwl_results}\";"                         >> "${rwl_rwl}"
echo "# connect strings either in URL or tnsnames entry that will be used when the  oltp  workload  is  executing"   >> "${rwl_rwl}"
echo "normal_connect := \"${db_url}\";"   >> "${rwl_rwl}"
echo "pool_connect   := \"${db_url}\";"   >> "${rwl_rwl}"
echo "batch_connect  := \"${db_url}\";"   >> "${rwl_rwl}"
echo "# used when schemas are created and filled with data"   >> "${rwl_rwl}"
echo "cruser_connect := \"${db_url}\";"   >> "${rwl_rwl}"
echo "cruser_username := \"system\";"   >> "${rwl_rwl}"
echo "cruser_password := \"${system_password}\";"   >> "${rwl_rwl}"
echo "# used during actual execution of your runs to primarily run queries against v$ tables etc" >> "${rwl_rwl}"
echo "system_connect := \"${db_url}\";"   >> "${rwl_rwl}"
echo "system_username := \"system\";"   >> "${rwl_rwl}"
echo "system_password := \"${system_password}\";"   >> "${rwl_rwl}"
echo "# Generate AWR reports from root container"           >> "${rwl_rwl}"
echo "sysawr_connect := \"${cdb_url}\";"   >> "${rwl_rwl}"
echo "sysawr_username := \"system\";"   >> "${rwl_rwl}"
echo "sysawr_password := \"${system_password}\";"   >> "${rwl_rwl}"
echo "# set the connection information for rwl repository"  >> "${rwl_rwl}"
echo "results_in_test := 1; "   >> "${rwl_rwl}"
echo "results_username := \"RWLOADSIM\";"   >> "${rwl_rwl}"
echo "results_password := \"${rwl_password}\";"   >> "${rwl_rwl}"
echo "results_connect := \"${db_url}\";"   >> "${rwl_rwl}"
echo "# where to find the files with ddl"   >> "${rwl_rwl}"
echo "rwloadsimdir := \"${rwl_dir}/admin\";"   >> "${rwl_rwl}"

echo "# Test users for the OLTP run"               >> "${rwl_rwl}"
echo "default_tablespace := \"data\";"             >> "${rwl_rwl}" 
echo "rwl_aw1_username := \"RWLAW1\";"             >> "${rwl_rwl}"
echo "rwl_aw1_password := \"${rwl_password}\";"    >> "${rwl_rwl}"
echo "rwl_aw2_username := \"RWLAW2\";"             >> "${rwl_rwl}"
echo "rwl_aw2_password := \"${rwl_password}\";"    >> "${rwl_rwl}"
echo "rwl_oe_username := \"RWLOE\";"               >> "${rwl_rwl}"
echo "rwl_oe_password := \"${rwl_password}\";"     >> "${rwl_rwl}"
echo "rwl_run1_username := \"RWLRUN1\"; "          >> "${rwl_rwl}"
echo "rwl_run1_password := \"${rwl_password}\";"   >> "${rwl_rwl}"
echo "rwl_run2_username := \"RWLRUN2\";"           >> "${rwl_rwl}"
echo "rwl_run2_password := \"${rwl_password}\";"   >> "${rwl_rwl}"
echo "rwl_run_like := \"RWLRUN_\";"                >> "${rwl_rwl}"
echo "rwl_title := \"rwl oltp development test\";" >> "${rwl_rwl}"
echo "gnuplotjs := \"/usr/share/gnuplot/4.6/js\";" >> "${rwl_rwl}"
echo "rwl_heading := \"heading for daily oltp\";"  >> "${rwl_rwl}"
echo "rwl_daily_html := \"daily.html\";"           >> "${rwl_rwl}"

# make sure the oracle user owns all the files
chown -R oracle:oinstall "${rwl_dir}"
chown -R oracle:oinstall "${rwl_output}"

#END
